kind: pipeline
name: default

steps:

#  - name: build
#    image: adoptopenjdk/openjdk11
#    commands:
#      - ./gradlew clean build

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: mdongel/myrepo
      auto_tag: true
      auto_tag_suffix: drone-build